server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/users
    username: postgres
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379


app:
  admin:
    email: ${ADMIN_EMAIL:admin@reservly.com}
    password: ${ADMIN_PASSWORD:admin12345}
  security:
    login:
      max-attempts: 5
      window: 15m

  jwt:
    secret: ${JWT_SECRET:HYgaLHwtjYEDH8n65MNOT6m3qD/Rl4OjNvNkgxXMgbmlR0EzhKcoUGJ1A6Uhu/V3}
    ttl: 15m
    refresh-ttl: 7d