services:
  adminer:
    image: adminer:5
    ports:
      - "8090:8080"

  auth-db:
    ports: ["5434:5432"]

  booking-db:
    ports: ["5433:5432"]

  payment-db:
    ports: ["5435:5432"]

  notification-db:
    ports: ["5436:5432"]

  redis:
    ports: ["6379:6379"]