server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:

          httpclient:
            connect-timeout: 2000
            response-timeout: 5s

          routes:
            - id: rooms
              uri: ${BOOKING_URI:http://localhost:8082}
              predicates:
                - Path=/api/rooms/**

            - id: bookings
              uri: ${BOOKING_URI:http://localhost:8082}
              predicates:
                - Path=/api/bookings/**

            - id: booking-docs
              uri: ${BOOKING_URI:http://localhost:8082}
              predicates:
                - Path=/api-docs/bookings/**
              filters:
                - RewritePath=/api-docs/bookings(?<segment>.*), /v3/api-docs$\{segment}

            - id: auth-login
              uri: ${AUTH_URI:http://localhost:8081}
              predicates:
                - Path=/api/auth/login
                - Method=POST
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 10

            - id: auth
              uri: ${AUTH_URI:http://localhost:8081}
              predicates:
                - Path=/api/auth/**

            - id: auth-docs
              uri: ${AUTH_URI:http://localhost:8081}
              predicates:
                - Path=/api-docs/auth/**
              filters:
                - RewritePath=/api-docs/auth(?<segment>.*), /v3/api-docs$\{segment}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379


app:
  jwt:
    secret: ${JWT_SECRET:HYgaLHwtjYEDH8n65MNOT6m3qD/Rl4OjNvNkgxXMgbmlR0EzhKcoUGJ1A6Uhu/V3}

springdoc:
  swagger-ui:
    urls:
      - name: booking-service
        url: /api-docs/bookings
      - name: auth-service
        url: /api-docs/auth


